# fish completion for wall-c

complete -c wall-c -s h -d "Show help message"
complete -c wall-c -s y -d "Skip confirmation prompt"
complete -c wall-c -l help -d "Show help message"
complete -c wall-c -l yes -d "Skip confirmation prompt"
complete -c wall-c -l version -d "Show version"
complete -c wall-c -l dry-run -d "Validate and print without sending"
complete -c wall-c -l quiet -d "Reduce normal output"
complete -c wall-c -l smart -d "Skip send if host appears awake and verify after send"
complete -c wall-c -s b -r -d "Broadcast IPv4 address"
complete -c wall-c -s p -r -d "Destination UDP port"
complete -c wall-c -s m -r -d "Target MAC address"
complete -c wall-c -l broadcast -r -d "Broadcast IPv4 address"
complete -c wall-c -l interface -r -d "Resolve broadcast from interface"
complete -c wall-c -l port -r -d "Destination UDP port"
complete -c wall-c -l mac -r -d "Target MAC address"
complete -c wall-c -l count -r -d "Repeat sends"
complete -c wall-c -l interval-ms -r -d "Delay between repeats in ms"
